apiVersion: apps/v1
kind: Deployment
metadata:
  name: prt-deploy
spec:
  replicas: 3
  template:
    metadata:
      name: demopod
      labels:
        app: myapp
    spec:
      containers:
        - name: democontainer
          image: danisheikh/demoimg
  selector:
    matchLabels:
      app: myapp
