apiVersion: apps/v1
kind: Deployment
metadata:
  name: prt-deploy
spec:
  replicas: 3
  template:
    metadata:
      name: prtpod
      labels:
        app: myapp
    spec:
      containers:
        - name: prtcontainer
          image: danisheikh/prtimage
  selcetor:
    matchLabels:
      app: myapp
